## Intro to pytorch

### installing pytorch
### importing pytorch and it's libraries with details 


In [36]:
#installing and importing python
%pip install torch
import torch

Note: you may need to restart the kernel to use updated packages.


In [37]:
x = torch.rand(5,3)
print(x)

tensor([[0.4257, 0.3521, 0.2521],
        [0.4291, 0.8968, 0.9885],
        [0.2370, 0.2826, 0.7648],
        [0.8774, 0.6014, 0.3544],
        [0.4791, 0.3440, 0.6635]])


In [38]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [39]:
x.device
# https://pytorch.org/docs/stable/torch.html

device(type='cpu')

In [40]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [41]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [42]:
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")

Using mps device


In [43]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [44]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
    

In [45]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [46]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

Predicted class: tensor([5], device='mps:0')


In [47]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [48]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [49]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [50]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[ 0.5045,  0.2235,  0.1649, -0.1753, -0.2173, -0.7098, -0.4001,  0.0637,
         -0.1794, -0.3401,  0.2447, -0.1697,  0.1386, -0.4964, -0.6730, -0.2360,
          0.0611, -0.0329, -0.7330, -0.1986],
        [-0.0762,  0.3129, -0.0626,  0.0877, -0.0617, -0.6467, -0.3878, -0.1990,
         -0.1770, -0.4700,  0.0824,  0.0932,  0.0802, -0.1845, -0.7105, -0.0584,
          0.3080, -0.0243, -0.9740, -0.3475],
        [ 0.0368,  0.2941,  0.1506, -0.0715, -0.1302, -0.6488, -0.6300, -0.2796,
         -0.3281, -0.4654,  0.4382, -0.2534,  0.2908, -0.4390, -0.7165, -0.0129,
          0.2936,  0.1237, -0.5363,  0.0376]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.5045, 0.2235, 0.1649, 0.0000, 0.0000, 0.0000, 0.0000, 0.0637, 0.0000,
         0.0000, 0.2447, 0.0000, 0.1386, 0.0000, 0.0000, 0.0000, 0.0611, 0.0000,
         0.0000, 0.0000],
        [0.0000, 0.3129, 0.0000, 0.0877, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0824, 0.0932, 0.0802, 0.0000, 0.00

In [51]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [52]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [53]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0287,  0.0047,  0.0055,  ...,  0.0328, -0.0332, -0.0299],
        [ 0.0146, -0.0010,  0.0291,  ...,  0.0189,  0.0212,  0.0054]],
       device='mps:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0268, -0.0034], device='mps:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[ 0.0209, -0.0246,  0.0191,  ...,  0.0399, -0.0266,  0.0117],
        [ 0.0354,  0.0399,  0.0377,  ..., -0.0418,  0.0092, -0.0315]],
       device='mps:0', grad_fn=<Slice